INSERT INTO countries (id,iso3166_a2name,name) VALUES (1,'AF','AFG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (2,'AX','ALA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (3,'AL','ALB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (4,'DZ','DZA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (5,'AS','ASM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (6,'AD','AND');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (7,'AO','AGO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (8,'AI','AIA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (9,'AQ','ATA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (10,'AG','ATG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (11,'AR','ARG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (12,'AM','ARM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (13,'AW','ABW');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (14,'AU','AUS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (15,'AT','AUT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (16,'AZ','AZE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (17,'BS','BHS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (18,'BH','BHR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (19,'BD','BGD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (20,'BB','BRB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (21,'BY','BLR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (22,'BE','BEL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (23,'BZ','BLZ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (24,'BJ','BEN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (25,'BM','BMU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (26,'BT','BTN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (27,'BO','BOL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (28,'BA','BIH');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (29,'BW','BWA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (30,'BV','BVT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (31,'BR','BRA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (32,'IO','IOT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (33,'BN','BRN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (34,'BG','BGR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (35,'BF','BFA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (36,'BI','BDI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (37,'KH','KHM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (38,'CM','CMR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (39,'CA','CAN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (40,'CV','CPV');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (41,'KY','CYM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (42,'CF','CAF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (43,'TD','TCD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (44,'CL','CHL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (45,'CN','CHN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (46,'CX','CXR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (47,'CC','CCK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (48,'CO','COL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (49,'KM','COM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (50,'CG','COG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (51,'CD','COD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (52,'CK','COK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (53,'CR','CRI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (54,'CI','CIV');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (55,'HR','HRV');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (56,'CU','CUB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (57,'CY','CYP');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (58,'CZ','CZE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (59,'DK','DNK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (60,'DJ','DJI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (61,'DM','DMA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (62,'DO','DOM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (63,'EC','ECU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (64,'EG','EGY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (65,'SV','SLV');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (66,'GQ','GNQ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (67,'ER','ERI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (68,'EE','EST');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (69,'ET','ETH');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (70,'FK','FLK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (71,'FO','FRO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (72,'FJ','FJI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (73,'FI','FIN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (74,'FR','FRA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (75,'GF','GUF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (76,'PF','PYF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (77,'TF','ATF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (78,'GA','GAB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (79,'GM','GMB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (80,'GE','GEO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (81,'DE','DEU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (82,'GH','GHA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (83,'GI','GIB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (84,'GR','GRC');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (85,'GL','GRL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (86,'GD','GRD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (87,'GP','GLP');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (88,'GU','GUM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (89,'GT','GTM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (90,'GG','GGY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (91,'GN','GIN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (92,'GW','GNB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (93,'GY','GUY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (94,'HT','HTI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (95,'HM','HMD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (96,'VA','VAT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (97,'HN','HND');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (98,'HK','HKG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (99,'HU','HUN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (100,'IS','ISL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (101,'IN','IND');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (102,'ID','IDN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (103,'IR','IRN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (104,'IQ','IRQ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (105,'IE','IRL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (106,'IM','IMM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (107,'IL','ISR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (108,'IT','ITA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (109,'JM','JAM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (110,'JP','JPN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (111,'JE','JEY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (112,'JO','JOR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (113,'KZ','KAZ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (114,'KE','KEN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (115,'KI','KIR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (116,'KP','PRK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (117,'KR','KOR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (118,'KW','KWT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (119,'KG','KGZ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (120,'LA','LAO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (121,'LV','LVA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (122,'LB','LBN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (123,'LS','LSO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (124,'LR','LBR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (125,'LY','LBY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (126,'LI','LIE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (127,'LT','LTU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (128,'LU','LUX');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (129,'MO','MAC');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (130,'MK','MKD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (131,'MG','MDG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (132,'MW','MWI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (133,'MY','MYS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (134,'MV','MDV');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (135,'ML','MLI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (136,'MT','MLT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (137,'MH','MHL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (138,'MQ','MTQ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (139,'MR','MRT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (140,'MU','MUS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (141,'YT','MYT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (142,'MX','MEX');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (143,'FM','FSM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (144,'MD','MDA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (145,'MC','MCO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (146,'MN','MNG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (147,'ME','MNE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (148,'MS','MSR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (149,'MA','MAR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (150,'MZ','MOZ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (151,'MM','MMR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (152,'NA','NAM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (153,'NR','NRU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (154,'NP','NPL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (155,'NL','NLD');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (156,'AN','ANT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (157,'NC','NCL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (158,'NZ','NZL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (159,'NI','NIC');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (160,'NE','NER');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (161,'NG','NGA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (162,'NU','NIU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (163,'NF','NFK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (164,'MP','MNP');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (165,'NO','NOR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (166,'OM','OMN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (167,'PK','PAK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (168,'PW','PLW');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (169,'PS','PSE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (170,'PA','PAN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (171,'PG','PNG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (172,'PY','PRY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (173,'PE','PER');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (174,'PH','PHL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (175,'PN','PCN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (176,'PL','POL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (177,'PT','PRT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (178,'PR','PRI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (179,'QA','QAT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (180,'RE','REU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (181,'RO','ROU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (182,'RU','RUS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (183,'RW','RWA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (184,'BL','BLM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (185,'SH','SHN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (186,'KN','KNA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (187,'LC','LCA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (188,'MT','MAF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (189,'PM','SPM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (190,'VC','VCT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (191,'WS','WSM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (192,'SM','SMR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (193,'ST','STP');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (194,'SA','SAU');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (195,'SN','SEN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (196,'RS','SRB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (197,'SC','SYC');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (198,'SL','SLE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (199,'SG','SGP');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (200,'SK','SVK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (201,'SI','SVN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (202,'SB','SLB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (203,'SO','SOM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (204,'ZA','ZAF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (205,'GS','SGS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (206,'ES','ESP');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (207,'LK','LKA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (208,'SD','SDN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (209,'SR','SUR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (210,'SJ','SJM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (211,'SZ','SWZ');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (212,'SE','SWE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (213,'CH','CHE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (214,'SY','SYR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (215,'TW','TWN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (216,'TJ','TJK');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (217,'TZ','TZA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (218,'TH','THA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (219,'TL','TLS');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (220,'TG','TGO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (221,'TK','TKL');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (222,'TO','TON');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (223,'TT','TTO');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (224,'TN','TUN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (225,'TR','TUR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (226,'TM','TKM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (227,'TC','TCA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (228,'TV','TUV');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (229,'UG','UGA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (230,'UA','UKR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (231,'AE','ARE');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (232,'GB','GBR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (233,'US','USA');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (234,'UM','UMI');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (235,'UY','URY');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (236,'UZ','UZB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (237,'VU','VUT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (238,'VA','VAT');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (239,'VE','VEN');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (240,'VN','VNM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (241,'VG','VGB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (242,'VI','VIR');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (243,'WF','WLF');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (244,'EH','ESH');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (245,'YE','YEM');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (246,'YU','YUG');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (247,'ZM','ZMB');
INSERT INTO countries (id,iso3166_a2name,name) VALUES (248,'ZW','ZWE');

INSERT INTO languages (id, version, name, iso639_1) VALUES (1, 1, 'Abkhaz', 'ab');
INSERT INTO languages (id, version, name, iso639_1) VALUES (2, 1, 'Afar', 'aa');
INSERT INTO languages (id, version, name, iso639_1) VALUES (3, 1, 'Afrikaans', 'af');
INSERT INTO languages (id, version, name, iso639_1) VALUES (4, 1, 'Akan', 'ak');
INSERT INTO languages (id, version, name, iso639_1) VALUES (5, 1, 'Albanian', 'sq');
INSERT INTO languages (id, version, name, iso639_1) VALUES (6, 1, 'Amharic', 'am');
INSERT INTO languages (id, version, name, iso639_1) VALUES (7, 1, 'Arabic', 'ar');
INSERT INTO languages (id, version, name, iso639_1) VALUES (8, 1, 'Aragonese', 'an');
INSERT INTO languages (id, version, name, iso639_1) VALUES (9, 1, 'Armenian', 'hy');
INSERT INTO languages (id, version, name, iso639_1) VALUES (10, 1, 'Assamese', 'as');
INSERT INTO languages (id, version, name, iso639_1) VALUES (11, 1, 'Avaric', 'av');
INSERT INTO languages (id, version, name, iso639_1) VALUES (12, 1, 'Avestan', 'ae');
INSERT INTO languages (id, version, name, iso639_1) VALUES (13, 1, 'Aymara', 'ay');
INSERT INTO languages (id, version, name, iso639_1) VALUES (14, 1, 'Azerbaijani', 'az');
INSERT INTO languages (id, version, name, iso639_1) VALUES (15, 1, 'Bambara', 'bm');
INSERT INTO languages (id, version, name, iso639_1) VALUES (16, 1, 'Bashkir', 'ba');
INSERT INTO languages (id, version, name, iso639_1) VALUES (17, 1, 'Basque', 'eu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (18, 1, 'Belarusian', 'be');
INSERT INTO languages (id, version, name, iso639_1) VALUES (19, 1, 'Bengali, Bangla', 'bn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (20, 1, 'Bihari', 'bh');
INSERT INTO languages (id, version, name, iso639_1) VALUES (21, 1, 'Bislama', 'bi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (22, 1, 'Bosnian', 'bs');
INSERT INTO languages (id, version, name, iso639_1) VALUES (23, 1, 'Breton', 'br');
INSERT INTO languages (id, version, name, iso639_1) VALUES (24, 1, 'Bulgarian', 'bg');
INSERT INTO languages (id, version, name, iso639_1) VALUES (25, 1, 'Burmese', 'my');
INSERT INTO languages (id, version, name, iso639_1) VALUES (26, 1, 'Catalan', 'ca');
INSERT INTO languages (id, version, name, iso639_1) VALUES (27, 1, 'Chamorro', 'ch');
INSERT INTO languages (id, version, name, iso639_1) VALUES (28, 1, 'Chechen', 'ce');
INSERT INTO languages (id, version, name, iso639_1) VALUES (29, 1, 'Chichewa, Chewa, Nyanja', 'ny');
INSERT INTO languages (id, version, name, iso639_1) VALUES (30, 1, 'Chinese', 'zh');
INSERT INTO languages (id, version, name, iso639_1) VALUES (31, 1, 'Chuvash', 'cv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (32, 1, 'Cornish', 'kw');
INSERT INTO languages (id, version, name, iso639_1) VALUES (33, 1, 'Corsican', 'co');
INSERT INTO languages (id, version, name, iso639_1) VALUES (34, 1, 'Cree', 'cr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (35, 1, 'Croatian', 'hr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (36, 1, 'Czech', 'cs');
INSERT INTO languages (id, version, name, iso639_1) VALUES (37, 1, 'Danish', 'da');
INSERT INTO languages (id, version, name, iso639_1) VALUES (38, 1, 'Divehi, Dhivehi, Maldivian', 'dv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (39, 1, 'Dutch', 'nl');
INSERT INTO languages (id, version, name, iso639_1) VALUES (40, 1, 'Dzongkha', 'dz');
INSERT INTO languages (id, version, name, iso639_1) VALUES (41, 1, 'English', 'en');
INSERT INTO languages (id, version, name, iso639_1) VALUES (42, 1, 'Esperanto', 'eo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (43, 1, 'Estonian', 'et');
INSERT INTO languages (id, version, name, iso639_1) VALUES (44, 1, 'Ewe', 'ee');
INSERT INTO languages (id, version, name, iso639_1) VALUES (45, 1, 'Faroese', 'fo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (46, 1, 'Fijian', 'fj');
INSERT INTO languages (id, version, name, iso639_1) VALUES (47, 1, 'Finnish', 'fi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (48, 1, 'French', 'fr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (49, 1, 'Fula, Fulah, Pulaar, Pular', 'ff');
INSERT INTO languages (id, version, name, iso639_1) VALUES (50, 1, 'Galician', 'gl');
INSERT INTO languages (id, version, name, iso639_1) VALUES (51, 1, 'Georgian', 'ka');
INSERT INTO languages (id, version, name, iso639_1) VALUES (52, 1, 'German', 'de');
INSERT INTO languages (id, version, name, iso639_1) VALUES (53, 1, 'Greek (modern)', 'el');
INSERT INTO languages (id, version, name, iso639_1) VALUES (54, 1, 'Guaraní', 'gn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (55, 1, 'Gujarati', 'gu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (56, 1, 'Haitian, Haitian Creole', 'ht');
INSERT INTO languages (id, version, name, iso639_1) VALUES (57, 1, 'Hausa', 'ha');
INSERT INTO languages (id, version, name, iso639_1) VALUES (58, 1, 'Hebrew (modern)', 'he');
INSERT INTO languages (id, version, name, iso639_1) VALUES (59, 1, 'Herero', 'hz');
INSERT INTO languages (id, version, name, iso639_1) VALUES (60, 1, 'Hindi', 'hi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (61, 1, 'Hiri Motu', 'ho');
INSERT INTO languages (id, version, name, iso639_1) VALUES (62, 1, 'Hungarian', 'hu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (63, 1, 'Interlingua', 'ia');
INSERT INTO languages (id, version, name, iso639_1) VALUES (64, 1, 'Indonesian', 'id');
INSERT INTO languages (id, version, name, iso639_1) VALUES (65, 1, 'Interlingue', 'ie');
INSERT INTO languages (id, version, name, iso639_1) VALUES (66, 1, 'Irish', 'ga');
INSERT INTO languages (id, version, name, iso639_1) VALUES (67, 1, 'Igbo', 'ig');
INSERT INTO languages (id, version, name, iso639_1) VALUES (68, 1, 'Inupiaq', 'ik');
INSERT INTO languages (id, version, name, iso639_1) VALUES (69, 1, 'Ido', 'io');
INSERT INTO languages (id, version, name, iso639_1) VALUES (70, 1, 'Icelandic', 'is');
INSERT INTO languages (id, version, name, iso639_1) VALUES (71, 1, 'Italian', 'it');
INSERT INTO languages (id, version, name, iso639_1) VALUES (72, 1, 'Inuktitut', 'iu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (73, 1, 'Japanese', 'ja');
INSERT INTO languages (id, version, name, iso639_1) VALUES (74, 1, 'Javanese', 'jv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (75, 1, 'Kalaallisut, Greenlandic', 'kl');
INSERT INTO languages (id, version, name, iso639_1) VALUES (76, 1, 'Kannada', 'kn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (77, 1, 'Kanuri', 'kr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (78, 1, 'Kashmiri', 'ks');
INSERT INTO languages (id, version, name, iso639_1) VALUES (79, 1, 'Kazakh', 'kk');
INSERT INTO languages (id, version, name, iso639_1) VALUES (80, 1, 'Khmer', 'km');
INSERT INTO languages (id, version, name, iso639_1) VALUES (81, 1, 'Kikuyu, Gikuyu', 'ki');
INSERT INTO languages (id, version, name, iso639_1) VALUES (82, 1, 'Kinyarwanda', 'rw');
INSERT INTO languages (id, version, name, iso639_1) VALUES (83, 1, 'Kyrgyz', 'ky');
INSERT INTO languages (id, version, name, iso639_1) VALUES (84, 1, 'Komi', 'kv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (85, 1, 'Kongo', 'kg');
INSERT INTO languages (id, version, name, iso639_1) VALUES (86, 1, 'Korean', 'ko');
INSERT INTO languages (id, version, name, iso639_1) VALUES (87, 1, 'Kurdish', 'ku');
INSERT INTO languages (id, version, name, iso639_1) VALUES (88, 1, 'Kwanyama, Kuanyama', 'kj');
INSERT INTO languages (id, version, name, iso639_1) VALUES (89, 1, 'Latin', 'la');
INSERT INTO languages (id, version, name, iso639_1) VALUES (90, 1, 'Luxembourgish, Letzeburgesch', 'lb');
INSERT INTO languages (id, version, name, iso639_1) VALUES (91, 1, 'Ganda', 'lg');
INSERT INTO languages (id, version, name, iso639_1) VALUES (92, 1, 'Limburgish, Limburgan, Limburger', 'li');
INSERT INTO languages (id, version, name, iso639_1) VALUES (93, 1, 'Lingala', 'ln');
INSERT INTO languages (id, version, name, iso639_1) VALUES (94, 1, 'Lao', 'lo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (95, 1, 'Lithuanian', 'lt');
INSERT INTO languages (id, version, name, iso639_1) VALUES (96, 1, 'Luba-Katanga', 'lu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (97, 1, 'Latvian', 'lv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (98, 1, 'Manx', 'gv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (99, 1, 'Macedonian', 'mk');
INSERT INTO languages (id, version, name, iso639_1) VALUES (100, 1, 'Malagasy', 'mg');
INSERT INTO languages (id, version, name, iso639_1) VALUES (101, 1, 'Malay', 'ms');
INSERT INTO languages (id, version, name, iso639_1) VALUES (102, 1, 'Malayalam', 'ml');
INSERT INTO languages (id, version, name, iso639_1) VALUES (103, 1, 'Maltese', 'mt');
INSERT INTO languages (id, version, name, iso639_1) VALUES (104, 1, 'M?ori', 'mi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (105, 1, 'Marathi', 'mr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (106, 1, 'Marshallese', 'mh');
INSERT INTO languages (id, version, name, iso639_1) VALUES (107, 1, 'Mongolian', 'mn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (108, 1, 'Nauruan', 'na');
INSERT INTO languages (id, version, name, iso639_1) VALUES (109, 1, 'Navajo, Navaho', 'nv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (110, 1, 'Northern Ndebele', 'nd');
INSERT INTO languages (id, version, name, iso639_1) VALUES (111, 1, 'Nepali', 'ne');
INSERT INTO languages (id, version, name, iso639_1) VALUES (112, 1, 'Ndonga', 'ng');
INSERT INTO languages (id, version, name, iso639_1) VALUES (113, 1, 'Norwegian Bokmål', 'nb');
INSERT INTO languages (id, version, name, iso639_1) VALUES (114, 1, 'Norwegian Nynorsk', 'nn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (115, 1, 'Norwegian', 'no');
INSERT INTO languages (id, version, name, iso639_1) VALUES (116, 1, 'Nuosu', 'ii');
INSERT INTO languages (id, version, name, iso639_1) VALUES (117, 1, 'Southern Ndebele', 'nr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (118, 1, 'Occitan', 'oc');
INSERT INTO languages (id, version, name, iso639_1) VALUES (119, 1, 'Ojibwe, Ojibwa', 'oj');
INSERT INTO languages (id, version, name, iso639_1) VALUES (120, 1, 'Old Church Slavonic, Church Slavonic, Old Bulgarian', 'cu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (121, 1, 'Oromo', 'om');
INSERT INTO languages (id, version, name, iso639_1) VALUES (122, 1, 'Oriya', 'or');
INSERT INTO languages (id, version, name, iso639_1) VALUES (123, 1, 'Ossetian, Ossetic', 'os');
INSERT INTO languages (id, version, name, iso639_1) VALUES (124, 1, 'Panjabi, Punjabi', 'pa');
INSERT INTO languages (id, version, name, iso639_1) VALUES (125, 1, 'P?li', 'pi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (126, 1, 'Persian (Farsi)', 'fa');
INSERT INTO languages (id, version, name, iso639_1) VALUES (127, 1, 'Polish', 'pl');
INSERT INTO languages (id, version, name, iso639_1) VALUES (128, 1, 'Pashto, Pushto', 'ps');
INSERT INTO languages (id, version, name, iso639_1) VALUES (129, 1, 'Portuguese', 'pt');
INSERT INTO languages (id, version, name, iso639_1) VALUES (130, 1, 'Quechua', 'qu');
INSERT INTO languages (id, version, name, iso639_1) VALUES (131, 1, 'Romansh', 'rm');
INSERT INTO languages (id, version, name, iso639_1) VALUES (132, 1, 'Kirundi', 'rn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (133, 1, 'Reunionese, Reunion Creole', 'rc');
INSERT INTO languages (id, version, name, iso639_1) VALUES (134, 1, 'Romanian', 'ro');
INSERT INTO languages (id, version, name, iso639_1) VALUES (135, 1, 'Russian', 'ru');
INSERT INTO languages (id, version, name, iso639_1) VALUES (136, 1, 'Sanskrit', 'sa');
INSERT INTO languages (id, version, name, iso639_1) VALUES (137, 1, 'Sardinian', 'sc');
INSERT INTO languages (id, version, name, iso639_1) VALUES (138, 1, 'Sindhi', 'sd');
INSERT INTO languages (id, version, name, iso639_1) VALUES (139, 1, 'Northern Sami', 'se');
INSERT INTO languages (id, version, name, iso639_1) VALUES (140, 1, 'Samoan', 'sm');
INSERT INTO languages (id, version, name, iso639_1) VALUES (141, 1, 'Sango', 'sg');
INSERT INTO languages (id, version, name, iso639_1) VALUES (142, 1, 'Serbian', 'sr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (143, 1, 'Scottish Gaelic, Gaelic', 'gd');
INSERT INTO languages (id, version, name, iso639_1) VALUES (144, 1, 'Shona', 'sn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (145, 1, 'Sinhalese, Sinhala', 'si');
INSERT INTO languages (id, version, name, iso639_1) VALUES (146, 1, 'Slovak', 'sk');
INSERT INTO languages (id, version, name, iso639_1) VALUES (147, 1, 'Slovene', 'sl');
INSERT INTO languages (id, version, name, iso639_1) VALUES (148, 1, 'Somali', 'so');
INSERT INTO languages (id, version, name, iso639_1) VALUES (149, 1, 'Southern Sotho', 'st');
INSERT INTO languages (id, version, name, iso639_1) VALUES (150, 1, 'Spanish', 'es');
INSERT INTO languages (id, version, name, iso639_1) VALUES (151, 1, 'Sundanese', 'su');
INSERT INTO languages (id, version, name, iso639_1) VALUES (152, 1, 'Swahili', 'sw');
INSERT INTO languages (id, version, name, iso639_1) VALUES (153, 1, 'Swati', 'ss');
INSERT INTO languages (id, version, name, iso639_1) VALUES (154, 1, 'Swedish', 'sv');
INSERT INTO languages (id, version, name, iso639_1) VALUES (155, 1, 'Tamil', 'ta');
INSERT INTO languages (id, version, name, iso639_1) VALUES (156, 1, 'Telugu', 'te');
INSERT INTO languages (id, version, name, iso639_1) VALUES (157, 1, 'Tajik', 'tg');
INSERT INTO languages (id, version, name, iso639_1) VALUES (158, 1, 'Thai', 'th');
INSERT INTO languages (id, version, name, iso639_1) VALUES (159, 1, 'Tigrinya', 'ti');
INSERT INTO languages (id, version, name, iso639_1) VALUES (160, 1, 'Tibetan Standard, Tibetan, Central', 'bo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (161, 1, 'Turkmen', 'tk');
INSERT INTO languages (id, version, name, iso639_1) VALUES (162, 1, 'Tagalog', 'tl');
INSERT INTO languages (id, version, name, iso639_1) VALUES (163, 1, 'Tswana', 'tn');
INSERT INTO languages (id, version, name, iso639_1) VALUES (164, 1, 'Tonga (Tonga Islands)', 'to');
INSERT INTO languages (id, version, name, iso639_1) VALUES (165, 1, 'Turkish', 'tr');
INSERT INTO languages (id, version, name, iso639_1) VALUES (166, 1, 'Tsonga', 'ts');
INSERT INTO languages (id, version, name, iso639_1) VALUES (167, 1, 'Tatar', 'tt');
INSERT INTO languages (id, version, name, iso639_1) VALUES (168, 1, 'Twi', 'tw');
INSERT INTO languages (id, version, name, iso639_1) VALUES (169, 1, 'Tahitian', 'ty');
INSERT INTO languages (id, version, name, iso639_1) VALUES (170, 1, 'Uyghur', 'ug');
INSERT INTO languages (id, version, name, iso639_1) VALUES (171, 1, 'Ukrainian', 'uk');
INSERT INTO languages (id, version, name, iso639_1) VALUES (172, 1, 'Urdu', 'ur');
INSERT INTO languages (id, version, name, iso639_1) VALUES (173, 1, 'Uzbek', 'uz');
INSERT INTO languages (id, version, name, iso639_1) VALUES (174, 1, 'Venda', 've');
INSERT INTO languages (id, version, name, iso639_1) VALUES (175, 1, 'Vietnamese', 'vi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (176, 1, 'Volapük', 'vo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (177, 1, 'Walloon', 'wa');
INSERT INTO languages (id, version, name, iso639_1) VALUES (178, 1, 'Welsh', 'cy');
INSERT INTO languages (id, version, name, iso639_1) VALUES (179, 1, 'Wolof', 'wo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (180, 1, 'Western Frisian', 'fy');
INSERT INTO languages (id, version, name, iso639_1) VALUES (181, 1, 'Xhosa', 'xh');
INSERT INTO languages (id, version, name, iso639_1) VALUES (182, 1, 'Yiddish', 'yi');
INSERT INTO languages (id, version, name, iso639_1) VALUES (183, 1, 'Yoruba', 'yo');
INSERT INTO languages (id, version, name, iso639_1) VALUES (184, 1, 'Zhuang, Chuang', 'za');
INSERT INTO languages (id, version, name, iso639_1) VALUES (185, 1, 'Zulu', 'zu');

INSERT INTO language_locales (id, version, locale) VALUES (1,1,'en');
INSERT INTO language_locales (id, version, locale) VALUES (2,1,'en_GB');
INSERT INTO language_locales (id, version, locale) VALUES (3,1,'en_US');
INSERT INTO language_locales (id, version, locale) VALUES (4,1,'de');
INSERT INTO language_locales (id, version, locale) VALUES (5,1,'de_AT');
INSERT INTO language_locales (id, version, locale) VALUES (6,1,'de_CH');
INSERT INTO language_locales (id, version, locale) VALUES (7,1,'de_DE');
INSERT INTO language_locales (id, version, locale) VALUES (8,1,'es');
INSERT INTO language_locales (id, version, locale) VALUES (9,1,'es_ES');
INSERT INTO language_locales (id, version, locale) VALUES (10,1,'fr');
INSERT INTO language_locales (id, version, locale) VALUES (11,1,'fr_BE');
INSERT INTO language_locales (id, version, locale) VALUES (12,1,'fr_CH');
INSERT INTO language_locales (id, version, locale) VALUES (13,1,'fr_FR');
INSERT INTO language_locales (id, version, locale) VALUES (14,1,'it');
INSERT INTO language_locales (id, version, locale) VALUES (15,1,'it_IT');
INSERT INTO language_locales (id, version, locale) VALUES (16,1,'nl');
INSERT INTO language_locales (id, version, locale) VALUES (17,1,'nl_BE');
INSERT INTO language_locales (id, version, locale) VALUES (18,1,'nl_NL');

INSERT INTO bundle_applications (id, version, name, default_locale_id) VALUES (1, 1, 'base-bundle-application', 1);

INSERT INTO basenames (id, version, name) VALUES (1,1,'base-resource-bundles');
INSERT INTO basenames (id, version, name) VALUES (2,1,'test');

INSERT INTO bundlenames (id, version, base_name_id, locale_id, owner_id) VALUES (1, 1, 1, 4, 1);
INSERT INTO bundlenames (id, version, base_name_id, locale_id, owner_id) VALUES (2, 1, 1, 2, 1);
INSERT INTO bundlenames (id, version, base_name_id, locale_id, owner_id) VALUES (3, 1, 2, 7, 1);
INSERT INTO bundlenames (id, version, base_name_id, locale_id, owner_id) VALUES (4, 1, 2, 3, 1);

INSERT INTO properties_keys (id, version, name) VALUES (1, 1, 'resource.bundles.test.label');
INSERT INTO properties_keys (id, version, name) VALUES (2, 1, 'com.example.gui.window.buttons.save');
INSERT INTO properties_keys (id, version, name) VALUES (3, 1, 'com.example.gui.window.title');
INSERT INTO properties_keys (id, version, name) VALUES (4, 1, 'com.example.gui.prop.with.params.label');
INSERT INTO properties_keys (id, version, name) VALUES (5, 1, 'com.example.gui.window.buttons.cancel');

INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (1, 1, 1, 'Erstes label', 1);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (2, 1, 1, 'First label', 2);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (3, 1, 2, 'Speichern', 3);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (4, 1, 3, 'Hallo, dort!', 3);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (5, 1, 4, 'Hallo ich bin {0} und komme aus {1}.', 3);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (6, 1, 5, 'Abbrechen', 3);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (7, 1, 2, 'Save', 4);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (8, 1, 3, 'Hello, there!', 4);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (9, 1, 4, 'Hello i am {0} and i come from {1}.', 4);
INSERT INTO resourcebundles (id, version, properties_key_id, value, bundlename_id) VALUES (10, 1, 5, 'Cancel', 4);
