MERGE INTO languages (id, version, name, iso639_1) VALUES (1, 1, 'Abkhaz', 'ab');
MERGE INTO languages (id, version, name, iso639_1) VALUES (2, 1, 'Afar', 'aa');
MERGE INTO languages (id, version, name, iso639_1) VALUES (3, 1, 'Afrikaans', 'af');
MERGE INTO languages (id, version, name, iso639_1) VALUES (4, 1, 'Akan', 'ak');
MERGE INTO languages (id, version, name, iso639_1) VALUES (5, 1, 'Albanian', 'sq');
MERGE INTO languages (id, version, name, iso639_1) VALUES (6, 1, 'Amharic', 'am');
MERGE INTO languages (id, version, name, iso639_1) VALUES (7, 1, 'Arabic', 'ar');
MERGE INTO languages (id, version, name, iso639_1) VALUES (8, 1, 'Aragonese', 'an');
MERGE INTO languages (id, version, name, iso639_1) VALUES (9, 1, 'Armenian', 'hy');
MERGE INTO languages (id, version, name, iso639_1) VALUES (10, 1, 'Assamese', 'as');
MERGE INTO languages (id, version, name, iso639_1) VALUES (11, 1, 'Avaric', 'av');
MERGE INTO languages (id, version, name, iso639_1) VALUES (12, 1, 'Avestan', 'ae');
MERGE INTO languages (id, version, name, iso639_1) VALUES (13, 1, 'Aymara', 'ay');
MERGE INTO languages (id, version, name, iso639_1) VALUES (14, 1, 'Azerbaijani', 'az');
MERGE INTO languages (id, version, name, iso639_1) VALUES (15, 1, 'Bambara', 'bm');
MERGE INTO languages (id, version, name, iso639_1) VALUES (16, 1, 'Bashkir', 'ba');
MERGE INTO languages (id, version, name, iso639_1) VALUES (17, 1, 'Basque', 'eu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (18, 1, 'Belarusian', 'be');
MERGE INTO languages (id, version, name, iso639_1) VALUES (19, 1, 'Bengali, Bangla', 'bn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (20, 1, 'Bihari', 'bh');
MERGE INTO languages (id, version, name, iso639_1) VALUES (21, 1, 'Bislama', 'bi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (22, 1, 'Bosnian', 'bs');
MERGE INTO languages (id, version, name, iso639_1) VALUES (23, 1, 'Breton', 'br');
MERGE INTO languages (id, version, name, iso639_1) VALUES (24, 1, 'Bulgarian', 'bg');
MERGE INTO languages (id, version, name, iso639_1) VALUES (25, 1, 'Burmese', 'my');
MERGE INTO languages (id, version, name, iso639_1) VALUES (26, 1, 'Catalan', 'ca');
MERGE INTO languages (id, version, name, iso639_1) VALUES (27, 1, 'Chamorro', 'ch');
MERGE INTO languages (id, version, name, iso639_1) VALUES (28, 1, 'Chechen', 'ce');
MERGE INTO languages (id, version, name, iso639_1) VALUES (29, 1, 'Chichewa, Chewa, Nyanja', 'ny');
MERGE INTO languages (id, version, name, iso639_1) VALUES (30, 1, 'Chinese', 'zh');
MERGE INTO languages (id, version, name, iso639_1) VALUES (31, 1, 'Chuvash', 'cv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (32, 1, 'Cornish', 'kw');
MERGE INTO languages (id, version, name, iso639_1) VALUES (33, 1, 'Corsican', 'co');
MERGE INTO languages (id, version, name, iso639_1) VALUES (34, 1, 'Cree', 'cr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (35, 1, 'Croatian', 'hr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (36, 1, 'Czech', 'cs');
MERGE INTO languages (id, version, name, iso639_1) VALUES (37, 1, 'Danish', 'da');
MERGE INTO languages (id, version, name, iso639_1) VALUES (38, 1, 'Divehi, Dhivehi, Maldivian', 'dv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (39, 1, 'Dutch', 'nl');
MERGE INTO languages (id, version, name, iso639_1) VALUES (40, 1, 'Dzongkha', 'dz');
MERGE INTO languages (id, version, name, iso639_1) VALUES (41, 1, 'English', 'en');
MERGE INTO languages (id, version, name, iso639_1) VALUES (42, 1, 'Esperanto', 'eo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (43, 1, 'Estonian', 'et');
MERGE INTO languages (id, version, name, iso639_1) VALUES (44, 1, 'Ewe', 'ee');
MERGE INTO languages (id, version, name, iso639_1) VALUES (45, 1, 'Faroese', 'fo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (46, 1, 'Fijian', 'fj');
MERGE INTO languages (id, version, name, iso639_1) VALUES (47, 1, 'Finnish', 'fi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (48, 1, 'French', 'fr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (49, 1, 'Fula, Fulah, Pulaar, Pular', 'ff');
MERGE INTO languages (id, version, name, iso639_1) VALUES (50, 1, 'Galician', 'gl');
MERGE INTO languages (id, version, name, iso639_1) VALUES (51, 1, 'Georgian', 'ka');
MERGE INTO languages (id, version, name, iso639_1) VALUES (52, 1, 'German', 'de');
MERGE INTO languages (id, version, name, iso639_1) VALUES (53, 1, 'Greek (modern)', 'el');
MERGE INTO languages (id, version, name, iso639_1) VALUES (54, 1, 'Guaraní', 'gn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (55, 1, 'Gujarati', 'gu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (56, 1, 'Haitian, Haitian Creole', 'ht');
MERGE INTO languages (id, version, name, iso639_1) VALUES (57, 1, 'Hausa', 'ha');
MERGE INTO languages (id, version, name, iso639_1) VALUES (58, 1, 'Hebrew (modern)', 'he');
MERGE INTO languages (id, version, name, iso639_1) VALUES (59, 1, 'Herero', 'hz');
MERGE INTO languages (id, version, name, iso639_1) VALUES (60, 1, 'Hindi', 'hi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (61, 1, 'Hiri Motu', 'ho');
MERGE INTO languages (id, version, name, iso639_1) VALUES (62, 1, 'Hungarian', 'hu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (63, 1, 'Interlingua', 'ia');
MERGE INTO languages (id, version, name, iso639_1) VALUES (64, 1, 'Indonesian', 'id');
MERGE INTO languages (id, version, name, iso639_1) VALUES (65, 1, 'Interlingue', 'ie');
MERGE INTO languages (id, version, name, iso639_1) VALUES (66, 1, 'Irish', 'ga');
MERGE INTO languages (id, version, name, iso639_1) VALUES (67, 1, 'Igbo', 'ig');
MERGE INTO languages (id, version, name, iso639_1) VALUES (68, 1, 'Inupiaq', 'ik');
MERGE INTO languages (id, version, name, iso639_1) VALUES (69, 1, 'Ido', 'io');
MERGE INTO languages (id, version, name, iso639_1) VALUES (70, 1, 'Icelandic', 'is');
MERGE INTO languages (id, version, name, iso639_1) VALUES (71, 1, 'Italian', 'it');
MERGE INTO languages (id, version, name, iso639_1) VALUES (72, 1, 'Inuktitut', 'iu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (73, 1, 'Japanese', 'ja');
MERGE INTO languages (id, version, name, iso639_1) VALUES (74, 1, 'Javanese', 'jv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (75, 1, 'Kalaallisut, Greenlandic', 'kl');
MERGE INTO languages (id, version, name, iso639_1) VALUES (76, 1, 'Kannada', 'kn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (77, 1, 'Kanuri', 'kr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (78, 1, 'Kashmiri', 'ks');
MERGE INTO languages (id, version, name, iso639_1) VALUES (79, 1, 'Kazakh', 'kk');
MERGE INTO languages (id, version, name, iso639_1) VALUES (80, 1, 'Khmer', 'km');
MERGE INTO languages (id, version, name, iso639_1) VALUES (81, 1, 'Kikuyu, Gikuyu', 'ki');
MERGE INTO languages (id, version, name, iso639_1) VALUES (82, 1, 'Kinyarwanda', 'rw');
MERGE INTO languages (id, version, name, iso639_1) VALUES (83, 1, 'Kyrgyz', 'ky');
MERGE INTO languages (id, version, name, iso639_1) VALUES (84, 1, 'Komi', 'kv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (85, 1, 'Kongo', 'kg');
MERGE INTO languages (id, version, name, iso639_1) VALUES (86, 1, 'Korean', 'ko');
MERGE INTO languages (id, version, name, iso639_1) VALUES (87, 1, 'Kurdish', 'ku');
MERGE INTO languages (id, version, name, iso639_1) VALUES (88, 1, 'Kwanyama, Kuanyama', 'kj');
MERGE INTO languages (id, version, name, iso639_1) VALUES (89, 1, 'Latin', 'la');
MERGE INTO languages (id, version, name, iso639_1) VALUES (90, 1, 'Luxembourgish, Letzeburgesch', 'lb');
MERGE INTO languages (id, version, name, iso639_1) VALUES (91, 1, 'Ganda', 'lg');
MERGE INTO languages (id, version, name, iso639_1) VALUES (92, 1, 'Limburgish, Limburgan, Limburger', 'li');
MERGE INTO languages (id, version, name, iso639_1) VALUES (93, 1, 'Lingala', 'ln');
MERGE INTO languages (id, version, name, iso639_1) VALUES (94, 1, 'Lao', 'lo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (95, 1, 'Lithuanian', 'lt');
MERGE INTO languages (id, version, name, iso639_1) VALUES (96, 1, 'Luba-Katanga', 'lu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (97, 1, 'Latvian', 'lv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (98, 1, 'Manx', 'gv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (99, 1, 'Macedonian', 'mk');
MERGE INTO languages (id, version, name, iso639_1) VALUES (100, 1, 'Malagasy', 'mg');
MERGE INTO languages (id, version, name, iso639_1) VALUES (101, 1, 'Malay', 'ms');
MERGE INTO languages (id, version, name, iso639_1) VALUES (102, 1, 'Malayalam', 'ml');
MERGE INTO languages (id, version, name, iso639_1) VALUES (103, 1, 'Maltese', 'mt');
MERGE INTO languages (id, version, name, iso639_1) VALUES (104, 1, 'M?ori', 'mi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (105, 1, 'Marathi', 'mr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (106, 1, 'Marshallese', 'mh');
MERGE INTO languages (id, version, name, iso639_1) VALUES (107, 1, 'Mongolian', 'mn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (108, 1, 'Nauruan', 'na');
MERGE INTO languages (id, version, name, iso639_1) VALUES (109, 1, 'Navajo, Navaho', 'nv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (110, 1, 'Northern Ndebele', 'nd');
MERGE INTO languages (id, version, name, iso639_1) VALUES (111, 1, 'Nepali', 'ne');
MERGE INTO languages (id, version, name, iso639_1) VALUES (112, 1, 'Ndonga', 'ng');
MERGE INTO languages (id, version, name, iso639_1) VALUES (113, 1, 'Norwegian Bokmål', 'nb');
MERGE INTO languages (id, version, name, iso639_1) VALUES (114, 1, 'Norwegian Nynorsk', 'nn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (115, 1, 'Norwegian', 'no');
MERGE INTO languages (id, version, name, iso639_1) VALUES (116, 1, 'Nuosu', 'ii');
MERGE INTO languages (id, version, name, iso639_1) VALUES (117, 1, 'Southern Ndebele', 'nr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (118, 1, 'Occitan', 'oc');
MERGE INTO languages (id, version, name, iso639_1) VALUES (119, 1, 'Ojibwe, Ojibwa', 'oj');
MERGE INTO languages (id, version, name, iso639_1) VALUES (120, 1, 'Old Church Slavonic, Church Slavonic, Old Bulgarian', 'cu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (121, 1, 'Oromo', 'om');
MERGE INTO languages (id, version, name, iso639_1) VALUES (122, 1, 'Oriya', 'or');
MERGE INTO languages (id, version, name, iso639_1) VALUES (123, 1, 'Ossetian, Ossetic', 'os');
MERGE INTO languages (id, version, name, iso639_1) VALUES (124, 1, 'Panjabi, Punjabi', 'pa');
MERGE INTO languages (id, version, name, iso639_1) VALUES (125, 1, 'P?li', 'pi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (126, 1, 'Persian (Farsi)', 'fa');
MERGE INTO languages (id, version, name, iso639_1) VALUES (127, 1, 'Polish', 'pl');
MERGE INTO languages (id, version, name, iso639_1) VALUES (128, 1, 'Pashto, Pushto', 'ps');
MERGE INTO languages (id, version, name, iso639_1) VALUES (129, 1, 'Portuguese', 'pt');
MERGE INTO languages (id, version, name, iso639_1) VALUES (130, 1, 'Quechua', 'qu');
MERGE INTO languages (id, version, name, iso639_1) VALUES (131, 1, 'Romansh', 'rm');
MERGE INTO languages (id, version, name, iso639_1) VALUES (132, 1, 'Kirundi', 'rn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (133, 1, 'Reunionese, Reunion Creole', 'rc');
MERGE INTO languages (id, version, name, iso639_1) VALUES (134, 1, 'Romanian', 'ro');
MERGE INTO languages (id, version, name, iso639_1) VALUES (135, 1, 'Russian', 'ru');
MERGE INTO languages (id, version, name, iso639_1) VALUES (136, 1, 'Sanskrit', 'sa');
MERGE INTO languages (id, version, name, iso639_1) VALUES (137, 1, 'Sardinian', 'sc');
MERGE INTO languages (id, version, name, iso639_1) VALUES (138, 1, 'Sindhi', 'sd');
MERGE INTO languages (id, version, name, iso639_1) VALUES (139, 1, 'Northern Sami', 'se');
MERGE INTO languages (id, version, name, iso639_1) VALUES (140, 1, 'Samoan', 'sm');
MERGE INTO languages (id, version, name, iso639_1) VALUES (141, 1, 'Sango', 'sg');
MERGE INTO languages (id, version, name, iso639_1) VALUES (142, 1, 'Serbian', 'sr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (143, 1, 'Scottish Gaelic, Gaelic', 'gd');
MERGE INTO languages (id, version, name, iso639_1) VALUES (144, 1, 'Shona', 'sn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (145, 1, 'Sinhalese, Sinhala', 'si');
MERGE INTO languages (id, version, name, iso639_1) VALUES (146, 1, 'Slovak', 'sk');
MERGE INTO languages (id, version, name, iso639_1) VALUES (147, 1, 'Slovene', 'sl');
MERGE INTO languages (id, version, name, iso639_1) VALUES (148, 1, 'Somali', 'so');
MERGE INTO languages (id, version, name, iso639_1) VALUES (149, 1, 'Southern Sotho', 'st');
MERGE INTO languages (id, version, name, iso639_1) VALUES (150, 1, 'Spanish', 'es');
MERGE INTO languages (id, version, name, iso639_1) VALUES (151, 1, 'Sundanese', 'su');
MERGE INTO languages (id, version, name, iso639_1) VALUES (152, 1, 'Swahili', 'sw');
MERGE INTO languages (id, version, name, iso639_1) VALUES (153, 1, 'Swati', 'ss');
MERGE INTO languages (id, version, name, iso639_1) VALUES (154, 1, 'Swedish', 'sv');
MERGE INTO languages (id, version, name, iso639_1) VALUES (155, 1, 'Tamil', 'ta');
MERGE INTO languages (id, version, name, iso639_1) VALUES (156, 1, 'Telugu', 'te');
MERGE INTO languages (id, version, name, iso639_1) VALUES (157, 1, 'Tajik', 'tg');
MERGE INTO languages (id, version, name, iso639_1) VALUES (158, 1, 'Thai', 'th');
MERGE INTO languages (id, version, name, iso639_1) VALUES (159, 1, 'Tigrinya', 'ti');
MERGE INTO languages (id, version, name, iso639_1) VALUES (160, 1, 'Tibetan Standard, Tibetan, Central', 'bo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (161, 1, 'Turkmen', 'tk');
MERGE INTO languages (id, version, name, iso639_1) VALUES (162, 1, 'Tagalog', 'tl');
MERGE INTO languages (id, version, name, iso639_1) VALUES (163, 1, 'Tswana', 'tn');
MERGE INTO languages (id, version, name, iso639_1) VALUES (164, 1, 'Tonga (Tonga Islands)', 'to');
MERGE INTO languages (id, version, name, iso639_1) VALUES (165, 1, 'Turkish', 'tr');
MERGE INTO languages (id, version, name, iso639_1) VALUES (166, 1, 'Tsonga', 'ts');
MERGE INTO languages (id, version, name, iso639_1) VALUES (167, 1, 'Tatar', 'tt');
MERGE INTO languages (id, version, name, iso639_1) VALUES (168, 1, 'Twi', 'tw');
MERGE INTO languages (id, version, name, iso639_1) VALUES (169, 1, 'Tahitian', 'ty');
MERGE INTO languages (id, version, name, iso639_1) VALUES (170, 1, 'Uyghur', 'ug');
MERGE INTO languages (id, version, name, iso639_1) VALUES (171, 1, 'Ukrainian', 'uk');
MERGE INTO languages (id, version, name, iso639_1) VALUES (172, 1, 'Urdu', 'ur');
MERGE INTO languages (id, version, name, iso639_1) VALUES (173, 1, 'Uzbek', 'uz');
MERGE INTO languages (id, version, name, iso639_1) VALUES (174, 1, 'Venda', 've');
MERGE INTO languages (id, version, name, iso639_1) VALUES (175, 1, 'Vietnamese', 'vi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (176, 1, 'Volapük', 'vo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (177, 1, 'Walloon', 'wa');
MERGE INTO languages (id, version, name, iso639_1) VALUES (178, 1, 'Welsh', 'cy');
MERGE INTO languages (id, version, name, iso639_1) VALUES (179, 1, 'Wolof', 'wo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (180, 1, 'Western Frisian', 'fy');
MERGE INTO languages (id, version, name, iso639_1) VALUES (181, 1, 'Xhosa', 'xh');
MERGE INTO languages (id, version, name, iso639_1) VALUES (182, 1, 'Yiddish', 'yi');
MERGE INTO languages (id, version, name, iso639_1) VALUES (183, 1, 'Yoruba', 'yo');
MERGE INTO languages (id, version, name, iso639_1) VALUES (184, 1, 'Zhuang, Chuang', 'za');
MERGE INTO languages (id, version, name, iso639_1) VALUES (185, 1, 'Zulu', 'zu');
