INSERT INTO countries (id,name,iso3166_a2name) VALUES (9, 'United Arab Emirates', 'AE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (15, 'Antigua and Barbuda', 'AG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (4, 'Anguilla', 'AI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (6, 'Albania', 'AL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (11, 'Armenia', 'AM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (3, 'Angola', 'AO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (13, 'Antarctica', 'AQ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (12, 'American Samoa', 'AS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (17, 'Austria', 'AT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (16, 'Australia', 'AU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (1, 'Aruba', 'AW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (18, 'Azerbaijan', 'AZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (27, 'Bosnia and Herzegovina', 'BA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (34, 'Barbados', 'BB');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (23, 'Bangladesh', 'BD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (22, 'Burkina Faso', 'BF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (24, 'Bulgaria', 'BG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (25, 'Bahrain', 'BH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (19, 'Burundi', 'BI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (21, 'Benin', 'BJ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (31, 'Bermuda', 'BM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (35, 'Brunei Darussalam', 'BN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (32, 'Bolivia', 'BO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (33, 'Brazil', 'BR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (26, 'Bahamas', 'BS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (36, 'Bhutan', 'BT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (37, 'Bouvet Island', 'BV');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (29, 'Belarus', 'BY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (30, 'Belize', 'BZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (40, 'Canada', 'CA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (41, 'Cocos (Keeling) Islands', 'CC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (39, 'Central African Republic,', 'CF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (48, 'Congo', 'CG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (42, 'Switzerland', 'CH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (49, 'Cook Islands', 'CK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (43, 'Chile', 'CL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (46, 'Cameroon', 'CM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (44, 'China', 'CN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (50, 'Colombia', 'CO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (53, 'Costa Rica', 'CR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (54, 'Cuba', 'CU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (55, 'Christmas Island', 'CX');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (57, 'Cyprus', 'CY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (58, 'Czechia', 'CZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (59, 'Germany', 'DE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (60, 'Djibouti', 'DJ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (62, 'Denmark', 'DK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (61, 'Dominica', 'DM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (64, 'Algeria', 'DZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (65, 'Ecuador', 'EC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (70, 'Estonia', 'EE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (66, 'Egypt', 'EG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (68, 'Western Sahara', 'EH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (67, 'Eritrea', 'ER');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (69, 'Spain', 'ES');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (71, 'Ethiopia', 'ET');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (72, 'Finland', 'FI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (74, 'Falkland Islands (Malvinas)', 'FK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (76, 'Faroe Islands', 'FO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (75, 'France', 'FR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (78, 'Gabon', 'GA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (79, 'United Kingdom', 'GB');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (90, 'Grenada', 'GD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (80, 'Georgia', 'GE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (93, 'French Guiana', 'GF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (82, 'Ghana', 'GH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (83, 'Gibraltar', 'GI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (91, 'Greenland', 'GL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (86, 'Gambia', 'GM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (84, 'Guinea', 'GN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (88, 'Equatorial Guinea', 'GQ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (89, 'Greece', 'GR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (92, 'Guatemala', 'GT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (94, 'Guam', 'GU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (95, 'Guyana', 'GY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (96, 'Hong Kong', 'HK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (98, 'Honduras', 'HN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (99, 'Croatia', 'HR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (100, 'Haiti', 'HT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (101, 'Hungary', 'HU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (102, 'Indonesia', 'ID');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (106, 'Ireland', 'IE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (110, 'Israel', 'IL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (103, 'Isle of Man', 'IM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (104, 'India', 'IN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (108, 'Iraq', 'IQ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (107, 'Iran', 'IR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (109, 'Iceland', 'IS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (111, 'Italy', 'IT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (113, 'Jersey', 'JE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (112, 'Jamaica', 'JM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (114, 'Jordan', 'JO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (115, 'Japan', 'JP');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (117, 'Kenya', 'KE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (118, 'Kyrgyzstan', 'KG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (119, 'Cambodia', 'KH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (120, 'Kiribati', 'KI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (121, 'Saint Kitts and Nevis', 'KN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (122, 'Korea (the Republic of)', 'KR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (123, 'Kuwait', 'KW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (56, 'Cayman Islands', 'KY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (116, 'Kazakhstan', 'KZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (125, 'Lebanon', 'LB');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (128, 'Saint Lucia', 'LC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (129, 'Liechtenstein', 'LI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (130, 'Sri Lanka', 'LK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (216, 'TJK', 'TJ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (243, 'YUG', 'YU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (7, 'Andorra', 'AD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (2, 'Afghanistan', 'AF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (10, 'Argentina', 'AR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (5, 'Åland Islands', 'AX');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (20, 'Belgium', 'BE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (28, 'Saint Barthélemy', 'BL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (246, 'Bonaire, Sint Eustatius and Saba', 'BQ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (38, 'Botswana', 'BW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (47, 'Congo, the Democratic Republic of the', 'CD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (45, 'Côte d''Ivoire', 'CI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (52, 'Cabo Verde', 'CV');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (247, 'Curaçao', 'CW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (63, 'Dominican Republic', 'DO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (73, 'Fiji', 'FJ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (77, 'Micronesia, Federated  of', 'FM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (81, 'Guernsey', 'GG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (85, 'Guadeloupe', 'GP');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (194, 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (87, 'Guinea-Bissau', 'GW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (97, 'Heard Island and McDonald Islands', 'HM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (105, 'British Indian Ocean Territory', 'IO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (51, 'Comoros', 'KM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (180, 'Korea (the Democratic People''s Republic of)', 'KP');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (124, 'Lao People''s Democratic Republic', 'LA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (126, 'Liberia', 'LR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (131, 'Lesotho', 'LS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (132, 'Lithuania', 'LT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (133, 'Luxembourg', 'LU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (134, 'Latvia', 'LV');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (127, 'Libya', 'LY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (137, 'Morocco', 'MA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (138, 'Monaco', 'MC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (139, 'Moldova', 'MD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (147, 'Montenegro', 'ME');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (248, 'Saint Martin (French part)', 'MF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (140, 'Madagascar', 'MG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (143, 'Marshall Islands', 'MH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (144, 'Macedonia, the former Yugoslav Republic of', 'MK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (145, 'Mali', 'ML');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (146, 'Myanmar', 'MM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (148, 'Mongolia', 'MN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (135, 'Macao', 'MO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (149, 'Northern Mariana Islands', 'MP');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (153, 'Martinique', 'MQ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (151, 'Mauritania', 'MR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (152, 'Montserrat', 'MS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (136, 'Malta', 'MT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (154, 'Mauritius', 'MU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (141, 'Maldives', 'MV');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (155, 'Malawi', 'MW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (142, 'Mexico', 'MX');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (156, 'Malaysia', 'MY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (150, 'Mozambique', 'MZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (158, 'Namibia', 'NA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (159, 'New Caledonia', 'NC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (160, 'Niger', 'NE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (161, 'Norfolk Island', 'NF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (162, 'Nigeria', 'NG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (163, 'Nicaragua', 'NI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (165, 'Netherlands', 'NL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (166, 'Norway', 'NO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (167, 'Nepal', 'NP');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (168, 'Nauru', 'NR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (164, 'Niue', 'NU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (169, 'New Zealand', 'NZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (170, 'Oman', 'OM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (172, 'Panama', 'PA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (174, 'Peru', 'PE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (184, 'French Polynesia', 'PF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (177, 'Papua New Guinea', 'PG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (175, 'Philippines', 'PH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (171, 'Pakistan', 'PK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (178, 'Poland', 'PL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (202, 'Saint Pierre and Miquelon', 'PM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (173, 'Pitcairn', 'PN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (179, 'Puerto Rico', 'PR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (183, 'Palestine, State of', 'PS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (181, 'Portugal', 'PT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (176, 'Palau', 'PW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (182, 'Paraguay', 'PY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (185, 'Qatar', 'QA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (186, 'Réunion', 'RE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (187, 'Romania', 'RO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (203, 'Serbia', 'RS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (188, 'Russian Federation', 'RU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (189, 'Rwanda', 'RW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (190, 'Saudi Arabia', 'SA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (197, 'Solomon Islands', 'SB');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (210, 'Seychelles', 'SC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (191, 'Sudan', 'SD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (208, 'Sweden', 'SE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (193, 'Singapore', 'SG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (195, 'Saint Helena, Ascension and Tristan da Cunha', 'SH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (207, 'Slovenia', 'SI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (196, 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (206, 'Slovakia', 'SK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (198, 'Sierra Leone', 'SL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (200, 'San Marino', 'SM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (192, 'Senegal', 'SN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (201, 'Somalia', 'SO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (205, 'Suriname', 'SR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (249, 'South Sudan', 'SS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (204, 'Sao Tome and Principe', 'ST');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (199, 'El Salvador', 'SV');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (250, 'Sint Maarten (Dutch part)', 'SX');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (211, 'Syrian Arab Republic', 'SY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (209, 'Swaziland', 'SZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (212, 'Turks and Caicos Islands', 'TC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (213, 'Chad', 'TD');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (14, 'French Southern Territories', 'TF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (214, 'Togo', 'TG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (215, 'Thailand', 'TH');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (217, 'Tokelau', 'TK');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (219, 'Timor-Leste', 'TL');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (218, 'Turkmenistan', 'TM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (222, 'Tunisia', 'TN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (220, 'Tonga', 'TO');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (223, 'Turkey', 'TR');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (221, 'Trinidad and Tobago', 'TT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (224, 'Tuvalu', 'TV');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (225, 'Taiwan', 'TW');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (226, 'Tanzania, United Republic of', 'TZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (228, 'Ukraine', 'UA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (227, 'Uganda', 'UG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (229, 'United  Minor Outlying Islands', 'UM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (231, 'United', 'US');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (230, 'Uruguay', 'UY');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (232, 'Uzbekistan', 'UZ');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (233, 'Holy See (Vatican City State)', 'VA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (234, 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (235, 'Venezuela, Bolivarian Republic of', 'VE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (236, 'Virgin Islands, British', 'VG');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (237, 'Virgin Islands, U.S.', 'VI');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (238, 'Viet Nam', 'VN');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (239, 'Vanuatu', 'VU');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (240, 'Wallis and Futuna', 'WF');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (241, 'Samoa', 'WS');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (242, 'Yemen', 'YE');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (157, 'Mayotte', 'YT');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (244, 'South Africa', 'ZA');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (245, 'Zambia', 'ZM');
INSERT INTO countries (id,name,iso3166_a2name) VALUES (251, 'Zimbabwe', 'ZW');