create table basenames (id int4 not null, version int4, name varchar(512), primary key (id));
create table bundle_application_language_locales (application_id int4 not null, language_locales_id int4 not null, primary key (application_id, language_locales_id));
create table bundle_applications (id int4 not null, version int4, name varchar(1024) unique, default_locale_id int4, primary key (id));
create table bundlenames (id int4 not null, version int4, filepath varchar(4096), base_name_id int4, locale_id int4, owner_id int4, primary key (id));
create table countries (id int4 not null, name varchar(64) unique, iso3166_a2name varchar(2), primary key (id));
create table language_locales (id int4 not null, version int4, locale varchar(64) unique, primary key (id));
create table languages (id int4 not null, version int4, name varchar(64) unique, iso639_1 varchar(2) unique, primary key (id));
create table properties_keys (id int4 not null, version int4, name varchar(1024), primary key (id));
create table properties_values (id int4 not null, version int4, name varchar(4096) unique, primary key (id));
create table resourcebundles (id int4 not null, version int4, bundlename_id int4, properties_key_id int4, properties_value_id int4, primary key (id));
